build:
  version: "1.0"

loans:
  message: "Welcome to Bank loans related to Production APIs "
  contactDetails:
    name: "Ms Ruby - Product Owner"
    email: "msruby@gmail.com"
  onCallSupport:
    - (555) 503-4254
    - (555) 595-0932