spring:
  application:
    name: "configServer"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "file:///home//marlone//Desktop//My projects//config"
#          search-locations: "classpath:/config"


server:
  port: 8071