spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to Bank accounts related to Production APIs "
  contactDetails:
    name: "Mad Max - Developer"
    email: "max@gmail.com"
  onCallSupport:
    - (555) 503-4254
    - (555) 595-0932