spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to Bank accounts related QA APIs "
  contactDetails:
    name: "Malcom X - Developer"
    email: "x@gmail.com"
  onCallSupport:
    - (555) 543-1454
    - (555) 345-9403